export const currentUser = store => store.employees
export const employee = store => store.auth.user
export const senders = store => store.senders
export const carriers = store => store.carriers
export const ttns = store => store.ttnData
export const employeesFilter = store => store.employees
export const ttnsFilter = store => store.TTNS
export const ttnFilter = store => store.TTN
export const authUser = ({auth}) => auth.user
export const company = ({auth}) => auth.user.company
